[package]
name = "mainner"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-variables = { path = "../libs/lib-variables" }
lib-functions = { path = "../libs/lib-functions" }
lib-flow = { path = "../libs/lib-flow" }